<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gurado_storefront"
 *
 * Auto generated by Extension Builder 2021-06-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'gurado Storefront',
    'description' => 'Kunden, ihre Gutscheine und Tickets ganz einfach die Typo3-Website einbinden und verkaufen',
    'category' => 'plugin',
    'author' => 'gurado',
    'author_email' => 'support@gurado.de',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
